apiVersion: apps/v1 
kind: Deployment
metadata:
  name: appldap
  labels:
    app: appldap
spec:
  selector:
    matchLabels:
      app: appldap
  replicas: 3 
  template:
    metadata:
      labels:
        app: appldap
    spec:
      containers:
      - name: appldap
        image: 10.128.0.2:5000/appldap:2.6
        ports:
        - containerPort: 80 
        env:
        - name: URLREAD
          value: "10.128.0.2:30009"
        - name: URLWRITE
          value: "10.128.0.2:30007"
---  
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: appldap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
