apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 10.128.0.2:5000/load-balancer:nginx1.8
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
          - name: IPSERVER1
            value: "app-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
  externalIPs:
    - 10.128.0.7
